### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by Silencezjl** [hankcs/ID-CNN-CWS#5]
#### Does anybody else really get a 90 points F1-Measure?????

**Comment by Silencezjl** [comment]
#### Finally, I use python 3.6 with warnings to run your code. And I got  a 92.32 points F1-Measure. It's so magical!!!!!!

**Comment by hankcs** [comment]
Yes, Python 3.5 won't work and outputs low scores. Currently the code stops training when score is lower than `90`, in order to save your time of tuning parameters. Stick to our documentation please (version must >= 3.6). 

Generally speaking, in iteration 1 you'll get a dev score around `92.3` with `pku cnn`, that's exactly what you reported. The final dev score will be around `96.1`, and final test score will be around `95.2`.  You can use the bundled official sighan score script to verify our result like:

```
$ python3 official_scorer.py --gold-file data/pku/raw/test.txt --test-out result/pku/cnn/2017-11-10_02-30-25/test-out.txt 
Evaluating [pku] using official SIGHAN score script...
pku
=== F MEASURE:  0.953
```

I attached a training log file for your perusal.
[info.log](https://github.com/hankcs/ID-CNN-CWS/files/1661428/info.log)

**Comment by Silencezjl** [comment]
Thanks a lot!
